# Generated by Django 6.0.2 on 2026-03-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth0_subject',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
