services:
  # 1. Django Service (Shopify Backend)
  shopify:
    build: ./Shopify_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Shopify_backend:/app
    env_file: .env
    # We keep ports open for debugging, but Nginx will handle traffic on port 80
    ports:
      - "8000:8000"

  # 2. FastAPI Service (Chat Logic)
  fastapi:
    build: ./ChatService_FastApi
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./ChatService_FastApi:/app
    env_file: .env
    ports:
      - "8001:8001"

  # 3. Django Celery Worker (password reset emails)
  worker:
    build: ./Shopify_backend
    command: celery -A config worker --loglevel=info
    volumes:
      - ./Shopify_backend:/app
    env_file: .env
    depends_on:
      - shopify

  # 4. Nginx Gateway: The single entry point for the frontend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shopify
      - fastapi

  frontend:
    build:
      context: ./Shopify
      target: build
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./Shopify:/app
      - /app/node_modules
    environment:
    - VITE_HOST=0.0.0.0
    - VITE_MIXPANEL_TOKEN=${VITE_MIXPANEL_TOKEN_DEV}
    - NODE_ENV=development
